# Generated by Django 5.2.3 on 2025-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
